Repository Quasi-Devs/Quasi-Bound, pull requests merged in 2021-01, with the labels that each got.

#29 (update) got spell card and character ability to work
  client/example.js
  client/src/components/GameEnv/2DEnv/2DEnv.jsx
  client/src/components/GameEnv/2DEnv/card.jsx
  client/src/components/GameEnv/GameEnv.jsx
Labels: 🚩 under review 🚩

#28 (Create) Live-time translation using google translate
  client/dist/index.html
  client/src/components/Homepage/Homepage.jsx
  client/src/components/Navbar.jsx
  package-lock.json
  package.json
  server/routes/discordAuth.js
Labels: core, enhancement, 🚩 under review 🚩

#32 (add) display for all user decks
  client/src/components/Deck/CardsDisplay.jsx
  client/src/components/Deck/Deck.jsx
  client/src/components/Deck/DeckHeader.jsx
  client/src/components/Deck/MyDecks.jsx
  client/src/components/Deck/Search.jsx
  client/src/components/Deck/myDecks.css
  client/src/components/Homepage/Drawer.jsx
  server/db/models/card.js
  server/db/models/deck.js
  server/db/models/user.js
  server/routes/dbRouter.js
Labels: core, 🚩 under review 🚩

#33 (refactor) image persistence with cloudinary API
  client/src/components/Deck/Upload.jsx
  package-lock.json
  package.json
  server/db/models/card.js
  server/index.js
Labels: core, enhancement, 🚩 under review 🚩

#35 (create) player match invites/profile refactor
  client/src/components/App.jsx
  client/src/components/GameEnv/2DEnv/2DEnv.jsx
  client/src/components/GameEnv/GameEnv.jsx
  client/src/components/PlayHub/PlayHub.jsx
  client/src/components/Profile/Profile.jsx
  server/index.js
  server/routes/discordAuth.js
  server/routes/googleAuth.js
Labels: core, 🚩 under review 🚩

#37 (update) deployment/database info & polish
  README.md
Labels: core, documentation

#41 (update) functionality w/ fly/magic damage
  client/example.js
  client/src/components/App.jsx
  client/src/components/GameEnv/2DEnv/2DEnv.jsx
  client/src/components/GameEnv/3DEnv/3DEnv.jsx
  client/src/components/GameEnv/GameEnv.jsx
  server/db/models/user.js
  server/routes/dbRouter.js
Labels: core
